Algoritmo "Notas"

Var nota1,nota2,nota3,nota4,media_anual:real

Inicio
  Escreval("Digite a primeira nota bimestral do aluno ")
  leia(nota1)
  Escreval("Digite a Segunda nota bimestral do aluno ")
  leia(nota2)
  escreval("Digite a terceira nota bimestral do aluno ")
  leia(nota3)
  escreval("Digite a quarta nota bimestral do aluno ")
  leia(nota4)
  media_anual<-(nota1+nota2+nota3+nota4)/4
  escreval("A média anual do aluno é= ",media_anual)


Fimalgoritmo